package interfaces;

import entidade.Doce;
import javax.swing.DefaultComboBoxModel;

public class PainelDoce extends javax.swing.JPanel {

    public PainelDoce() {
        initComponents();
        Doce.Recheio[] recheios = Doce.Recheio.values();
        DefaultComboBoxModel<Doce.Recheio> model = new DefaultComboBoxModel<>(recheios);
        recheioComboBox.setModel(model);
        recheioComboBox.setSelectedItem(recheios[0]);
    }
    
    public void setSabor(String sabor){
       if(!sabor.isEmpty())
           saborTextField.setText(sabor);
    }
    
    public String getSabor(){
        return saborTextField.getText();
    }
    
    public Doce.Recheio getRecheio(){
        Doce.Recheio recheio = (Doce.Recheio)recheioComboBox.getSelectedItem();
        return recheio;
    }
    
    public void setRecheio(int indice_recheio){
        Doce.Recheio [] recheios = Doce.Recheio.values();
        recheioComboBox.setSelectedItem(recheios[indice_recheio]);
    }
    
    public void limparCampos(){
        saborTextField.setText("");
        recheioComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        saborLabel = new javax.swing.JLabel();
        recheioLabel = new javax.swing.JLabel();
        saborTextField = new javax.swing.JTextField();
        recheioComboBox = new javax.swing.JComboBox();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0, 7, 0};
        setLayout(layout);

        saborLabel.setText("Sabor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(saborLabel, gridBagConstraints);

        recheioLabel.setText("Recheio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(recheioLabel, gridBagConstraints);

        saborTextField.setPreferredSize(new java.awt.Dimension(200, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(saborTextField, gridBagConstraints);

        recheioComboBox.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(recheioComboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox recheioComboBox;
    private javax.swing.JLabel recheioLabel;
    private javax.swing.JLabel saborLabel;
    private javax.swing.JTextField saborTextField;
    // End of variables declaration//GEN-END:variables
}
